### ISSUE TITLE
error

### ISSUE THREAD

**Issue by banxian2** [ganjsmoke/plaza-finance-bot#3]
const chalk = require('chalk');  // For colorful logging
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /data1/node/plaza-finance-bot/node_modules/chalk/source/index.js from /data1/node/plaza-finance-bot/index.js not supported.
Instead change the require of /data1/node/plaza-finance-bot/node_modules/chalk/source/index.js in /data1/node/plaza-finance-bot/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data1/node/plaza-finance-bot/index.js:3:15) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by ganjsmoke** [comment]
> const chalk = require('chalk'); // For colorful logging ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /data1/node/plaza-finance-bot/node_modules/chalk/source/index.js from /data1/node/plaza-finance-bot/index.js not supported. Instead change the require of /data1/node/plaza-finance-bot/node_modules/chalk/source/index.js in /data1/node/plaza-finance-bot/index.js to a dynamic import() which is available in all CommonJS modules. at Object. (/data1/node/plaza-finance-bot/index.js:3:15) { code: 'ERR_REQUIRE_ESM' }

npm install chalk@2
